---

- name: Installation MySQL
  hosts: database
  remote_user: admuser
  become: true
  pre_tasks:
    - name: Lecture du fichier de variable
      include_vars: ./group_vars/db.yml
  roles:
  - mysql

- name: Installation Serveur WEB
  hosts: web
  remote_user: admuser
  become: true
  roles:
  - web-php-ftp

- name: Installation WordPress
  hosts: web
  remote_user: admuser
  become: true
  roles:
  - wordpress