---

- name: Téléchargement de WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extraction de WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Import VirtualHost (wordpress.conf)
  copy:
    src: ./template/wordpress.conf
    dest: /etc/apache2/sites-available/wordpress.conf
    mode: 0640

- name: Activer VirtualHost (wordpress.conf)
  command: a2ensite wordpress.conf

- name: Desactiver 000-default
  command: a2dissite 000-default.conf
  notify:
    - restart apache

- name: Import configuration WordPress (wp-config.php)
  template: 
    src: ./template/wp-config.php
    dest: /var/www/wordpress