---
# Tasks file for PHP

- name: Installation de PHP + Dépendances
  become: yes
  apt: name={{item}} state=present
  with_items:
    - php
    - php-mysql
    - php-common
    - php-mysql
    - php-tidy
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - php-memcached
    - php-curl
    - php-zip
